export const BOOKING_STATES = [
  'REQUESTED',
  'PAYMENT_CONFIRMED',
  'SEARCHING_PARTNER',
  'PARTNER_ASSIGNED',
  'ON_THE_WAY',
  'SHOOT_STARTED',
  'SHOOT_COMPLETED',
  'DATA_PENDING',
  'DATA_SUBMITTED',
  'CUSTOMER_CONFIRMED',
  'PAYOUT_RELEASED',
  'COMPLETED',
] as const;

export type BookingState = (typeof BOOKING_STATES)[number];

export const BOOKING_TRANSITIONS: Record<BookingState, BookingState[]> = {
  REQUESTED: ['PAYMENT_CONFIRMED'],
  PAYMENT_CONFIRMED: ['SEARCHING_PARTNER'],
  SEARCHING_PARTNER: ['PARTNER_ASSIGNED'],
  PARTNER_ASSIGNED: ['ON_THE_WAY'],
  ON_THE_WAY: ['SHOOT_STARTED'],
  SHOOT_STARTED: ['SHOOT_COMPLETED'],
  SHOOT_COMPLETED: ['DATA_PENDING'],
  DATA_PENDING: ['DATA_SUBMITTED'],
  DATA_SUBMITTED: ['CUSTOMER_CONFIRMED'],
  CUSTOMER_CONFIRMED: ['PAYOUT_RELEASED'],
  PAYOUT_RELEASED: ['COMPLETED'],
  COMPLETED: [],
};

export function canTransition(from: BookingState, to: BookingState) {
  return BOOKING_TRANSITIONS[from].includes(to);
}
